services:
  postgres:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env.test
    ports:
      - 4000:4000
    depends_on:
      postgres:
        condition: service_healthy
    command: ["npm", "start"]
